albedo:
    rpc:
        namespace: thrift-snowserv
        hostUrl: localhost:8181 #rpc port
        zookeeper:
                connectString: 192.168.6.128:2181,192.168.6.128:2182,192.168.6.128:2183


